"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import { ArrowRight, BarChart3, Check, ChevronRight, CirclePlus, Loader2, LogOut, MessageSquare, Plus, Search, SlidersHorizontal, Trash2, UserRound, X } from "lucide-react";
import { api, defaultConfig, money, pct, supabase } from "@/lib/api";
import type { Backtest, BucketPaperActivity, Config, ETF, Holding, Preview, Series, WalkForward } from "@/lib/types";
import PerformanceChart from "./PerformanceChart";
import ThesisChat from "./ThesisChat";

const newPortfolio = () => ({ name: "Untitled portfolio", symbol: "CUSTOM", description: "", holdings: [] as Holding[] });
const WEIGHT_TOLERANCE = 1e-6;
const ENTRY_PERIODS = [
  ["5 years", (date: Date) => date.setFullYear(date.getFullYear() - 5)],
  ["1 year", (date: Date) => date.setFullYear(date.getFullYear() - 1)],
  ["6 months", (date: Date) => date.setMonth(date.getMonth() - 6)],
  ["3 months", (date: Date) => date.setMonth(date.getMonth() - 3)],
  ["1 month", (date: Date) => date.setMonth(date.getMonth() - 1)],
  ["2 weeks", (date: Date) => date.setDate(date.getDate() - 14)],
  ["1 week", (date: Date) => date.setDate(date.getDate() - 7)],
] as const;

function normalizedHoldings(holdings: Holding[]) {
  const total = holdings.reduce((sum, holding) => sum + holding.target_weight, 0);
  if (!holdings.length || total <= 0) return holdings;
  let allocated = 0;
  return holdings.map((holding, index) => {
    const target_weight = index === holdings.length - 1
      ? 1 - allocated
      : holding.target_weight / total;
    allocated += target_weight;
    return { ...holding, target_weight };
  });
}

export default function Workspace() {
  const router = useRouter();
  const pathname = usePathname();
  const [portfolios, setPortfolios] = useState<ETF[]>([]);
  const [selected, setSelected] = useState<ETF | null>(null);
  const [draft, setDraft] = useState(newPortfolio);
  const [config, setConfig] = useState<Config>(defaultConfig);
  const [result, setResult] = useState<Backtest | null>(null);
  const [series, setSeries] = useState<Series | null>(null);
  const [query, setQuery] = useState("");
  const [matches, setMatches] = useState<{ ticker: string; company_name: string; theme_tag: string }[]>([]);
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [range, setRange] = useState("5Y");
  const [allocationMode, setAllocationMode] = useState<"percent" | "dollars">("percent");
  const [allocationInputs, setAllocationInputs] = useState<Record<string, string>>({});
  const [profileOpen, setProfileOpen] = useState(false);
  const [thesisModalOpen, setThesisModalOpen] = useState(false);
  const [userEmail, setUserEmail] = useState("");
  const [paperInvestment, setPaperInvestment] = useState("1000");
  const [paperPreview, setPaperPreview] = useState<Preview | null>(null);
  const [paperActivity, setPaperActivity] = useState<BucketPaperActivity[]>([]);
  const [walkForward, setWalkForward] = useState<WalkForward | null>(null);
  const isDashboard = pathname === "/" || pathname === "/dashboard";
  const total = useMemo(() => draft.holdings.reduce((sum, holding) => sum + holding.target_weight, 0), [draft.holdings]);
  const valid = draft.holdings.length > 0 && (allocationMode === "dollars" ? total > 0 : Math.abs(total - 1) <= WEIGHT_TOLERANCE);
  const metrics = result?.metrics ?? {};
  const activeJob = result?.status === "queued" || result?.status === "running";
  const loadPortfolios = useCallback(async () => { const list = await api<ETF[]>("/v1/etfs"); setPortfolios(list); return list; }, []);
  const openPortfolio = useCallback(async (portfolio: ETF) => {
    setSelected(portfolio); setDraft({ name: portfolio.name, symbol: portfolio.symbol, description: portfolio.description, holdings: portfolio.holdings });
    setConfig(portfolio.config && Object.keys(portfolio.config).length ? portfolio.config : defaultConfig());
    const history = await api<Backtest[]>(`/v1/etfs/${portfolio.id}/backtests`); const latest = history[0] ?? null; setResult(latest); if (latest) setConfig(latest.config);
  }, []);
  useEffect(() => { let cancelled = false; loadPortfolios().then(async (list) => { if (cancelled) return; const id = pathname.split("/")[2]; if (id === "new") { setSelected(null); setDraft(newPortfolio()); setResult(null); return; } const portfolio = id ? list.find((item) => item.id === id) : list[0]; if (portfolio && !isDashboard) await openPortfolio(portfolio); }).catch((reason) => setError(reason.message)); return () => { cancelled = true; }; }, [pathname, isDashboard, loadPortfolios, openPortfolio]);
  useEffect(() => { if (!result || !activeJob) return; const interval = window.setInterval(() => api<Backtest>(`/v1/backtests/${result.id}`).then(setResult).catch((reason) => setError(reason.message)), 1000); return () => window.clearInterval(interval); }, [result, activeJob]);
  useEffect(() => { if (result?.status !== "completed") { setSeries(null); return; } api<Series>(`/v1/backtests/${result.id}/series?range=${range}`).then(setSeries).catch((reason) => setError(reason.message)); }, [result?.id, result?.status, range]);
  useEffect(() => { if (!query.trim()) { setMatches([]); return; } const timer = window.setTimeout(() => api<typeof matches>(`/v1/market/symbols?q=${encodeURIComponent(query)}`).then(setMatches).catch((reason) => setError(reason.message)), 200); return () => window.clearTimeout(timer); }, [query]);
  useEffect(() => { supabase?.auth.getUser().then(({ data }) => setUserEmail(data.user?.email ?? "")); }, []);
  const loadPaperActivity = useCallback(async (portfolioId: string) => {
    const activity = await api<BucketPaperActivity[]>(`/v1/etfs/${portfolioId}/paper-orders`);
    setPaperActivity(activity);
  }, []);
  useEffect(() => { if (selected) void loadPaperActivity(selected.id).catch((reason) => setError(reason.message)); else { setPaperActivity([]); setPaperPreview(null); } }, [selected?.id, loadPaperActivity]);
  async function save(configOverride = config) { if (!valid) throw new Error("Add at least one holding and set weights to 100%."); const dollarTotal = allocationMode === "dollars" ? total * configOverride.initial_capital : null; const savedConfig = dollarTotal && Number.isFinite(dollarTotal) ? { ...configOverride, initial_capital: dollarTotal } : configOverride; if (savedConfig !== config) setConfig(savedConfig); const payload = { ...draft, config: savedConfig, holdings: normalizedHoldings(draft.holdings) }; const portfolio = selected ? await api<ETF>(`/v1/etfs/${selected.id}`, { method: "PATCH", body: JSON.stringify({ ...payload, expected_version: selected.version }) }) : await api<ETF>("/v1/etfs", { method: "POST", body: JSON.stringify(payload) }); setSelected(portfolio); setDraft({ name: portfolio.name, symbol: portfolio.symbol, description: portfolio.description, holdings: portfolio.holdings }); await loadPortfolios(); return portfolio; }
  async function runBacktest(configOverride = config) { setBusy("backtest"); setError(""); try { const backtestConfig = allocationMode === "dollars" ? { ...configOverride, initial_capital: total * configOverride.initial_capital } : configOverride; const portfolio = await save(backtestConfig); const backtest = await api<Backtest>("/v1/backtests", { method: "POST", body: JSON.stringify({ ...backtestConfig, etf_id: portfolio.id, portfolio_version: portfolio.version }) }); setResult(backtest); setNotice("Backtest started. Results will appear here when ready."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not run backtest."); } finally { setBusy(""); } }
  function addHolding(item: (typeof matches)[number]) { if (draft.holdings.some((holding) => holding.ticker === item.ticker)) return; setDraft((current) => ({ ...current, holdings: [...current.holdings, { ...item, target_weight: 0, rationale: "", sources: [] }] })); setQuery(""); }
  function changeAllocation(index: number, value: string) { setAllocationInputs((current) => ({ ...current, [draft.holdings[index].ticker]: value })); const amount = Number(value); const target_weight = Number.isFinite(amount) ? allocationMode === "percent" ? amount / 100 : amount / config.initial_capital : 0; setDraft((current) => ({ ...current, holdings: current.holdings.map((holding, holdingIndex) => holdingIndex === index ? { ...holding, target_weight } : holding) })); }
  function allocationValue(holding: Holding) { if (holding.ticker in allocationInputs) return allocationInputs[holding.ticker]; const value = allocationMode === "percent" ? holding.target_weight * 100 : holding.target_weight * config.initial_capital; return value === 0 ? "" : String(value); }
  function entryPeriodConfig(adjust: (date: Date) => number) { const end = new Date(); end.setDate(end.getDate() - 1); const start = new Date(end); adjust(start); return { ...config, start_date: start.toISOString().slice(0, 10), end_date: end.toISOString().slice(0, 10) }; }
  function setEntryPeriod(adjust: (date: Date) => number) { setConfig(entryPeriodConfig(adjust)); }
  function runEntryPeriod(adjust: (date: Date) => number) { const scenario = entryPeriodConfig(adjust); setConfig(scenario); void runBacktest(scenario); }
  function createFromThesis(proposal: { name: string; description: string; symbol?: string; holdings: Holding[] }) { setSelected(null); setDraft({ name: proposal.name, symbol: proposal.symbol || "CUSTOM", description: proposal.description, holdings: proposal.holdings }); setResult(null); setAllocationMode("percent"); setAllocationInputs({}); setNotice("Custom ETF draft created. Review the allocation, then save or run a backtest."); }
  async function createBucketFromThesis(proposal: { name: string; description: string; symbol?: string; holdings: Holding[] }) { const portfolio = await api<ETF>("/v1/etfs", { method: "POST", body: JSON.stringify({ name: proposal.name, symbol: proposal.symbol || "CUSTOM", description: proposal.description, holdings: normalizedHoldings(proposal.holdings), config }) }); await loadPortfolios(); setThesisModalOpen(false); router.push(`/etf/${portfolio.id}`); }
  async function optimizeWeights() { setBusy("optimize"); setError(""); try { const portfolio = await save(); const optimized = await api<{ holdings: Holding[]; warning: string; constraints: { candidates_tested: number } }>(`/v1/etfs/${portfolio.id}/optimize`, { method: "POST", body: JSON.stringify({ ...config, portfolio_version: portfolio.version }) }); setSelected(portfolio); setDraft((current) => ({ ...current, holdings: optimized.holdings })); setAllocationMode("percent"); setAllocationInputs({}); setResult(null); setNotice(`Optimized ${optimized.constraints.candidates_tested} whole-percent allocations. ${optimized.warning}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not optimize weights."); } finally { setBusy(""); } }
  async function runWalkForward() { setBusy("walk-forward"); setError(""); try { const portfolio = await save(); const validation = await api<WalkForward>(`/v1/etfs/${portfolio.id}/walk-forward`, { method: "POST", body: JSON.stringify({ ...config, portfolio_version: portfolio.version, test_sessions: 63 }) }); setWalkForward(validation); setNotice("Walk-forward validation completed using three unseen 63-session test windows."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not run walk-forward validation."); } finally { setBusy(""); } }
  async function previewPaperDeployment() { setBusy("paper-preview"); setError(""); try { const investment = Number(paperInvestment); if (!Number.isFinite(investment) || investment < 1) throw new Error("Enter a paper investment of at least $1."); const portfolio = await save(); const preview = await api<Preview>("/v1/orders/preview", { method: "POST", body: JSON.stringify({ etf_id: portfolio.id, portfolio_version: portfolio.version, investment }) }); setPaperPreview(preview); await loadPaperActivity(portfolio.id); setNotice("Paper order preview ready. Review the allocation below before submitting."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not create paper-order preview."); } finally { setBusy(""); } }
  async function submitPaperDeployment() { if (!paperPreview) return; if (!window.confirm("Submit these market buy orders to Alpaca Paper Trading? This uses virtual funds only and cannot be undone from Aquarius.")) return; setBusy("paper-submit"); setError(""); try { const response = await api<{ orders: { status: string }[] }>("/v1/orders/paper", { method: "POST", body: JSON.stringify({ preview_id: paperPreview.id, confirmed: true }) }); setNotice(`${response.orders.length} paper order${response.orders.length === 1 ? "" : "s"} submitted. Alpaca will report fills after the market processes them.`); setPaperPreview(null); if (selected) await loadPaperActivity(selected.id); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not submit paper orders."); } finally { setBusy(""); } }
  async function refreshPaperActivity() { if (!selected) return; setBusy("paper-refresh"); setError(""); try { for (const preview of paperActivity) { if (preview.orders.length) await api(`/v1/orders/${preview.id}/reconcile`, { method: "POST" }); } await loadPaperActivity(selected.id); setNotice("Paper-order status refreshed from Alpaca."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not refresh paper-order status."); } finally { setBusy(""); } }
  async function removePortfolio(portfolio: ETF) { if (!window.confirm(`Delete “${portfolio.name}” and all of its backtests? This cannot be undone.`)) return; try { setBusy(`delete-${portfolio.id}`); await api<void>(`/v1/etfs/${portfolio.id}`, { method: "DELETE" }); const remaining = await loadPortfolios(); if (selected?.id === portfolio.id) { setSelected(null); setDraft(newPortfolio()); setResult(null); router.push("/dashboard"); } setNotice("Container deleted."); if (!remaining.length) setResult(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not delete the container."); } finally { setBusy(""); } }
  async function signOut() { await supabase?.auth.signOut(); router.push("/"); }
  const shellProps = { portfolios, onNew: () => router.push("/etf/new"), userEmail, profileOpen, setProfileOpen, onSignOut: signOut };
  if (isDashboard) return <Shell {...shellProps}><section className="bare-hero"><span>AQUARIUS BASKETS</span><h1>Build a basket.<br />Test the thesis.</h1><p>Create stock and ETF baskets, set target weights, and compare the long-term outcome against a benchmark.</p><div className="hero-actions"><button className="primary" onClick={() => router.push("/etf/new")}><Plus size={16} /> New basket</button><button className="thesis-modal-trigger" onClick={() => setThesisModalOpen(true)}><MessageSquare size={16} /> Create with AI</button></div></section>{thesisModalOpen && <div className="thesis-modal-backdrop" role="dialog" aria-modal="true" aria-label="Create basket with AI"><div className="thesis-modal"><button className="close-modal" aria-label="Close AI thesis chat" onClick={() => setThesisModalOpen(false)}><X size={18} /></button><ThesisChat onCreate={createBucketFromThesis} /></div></div>}<div className="section-heading"><div><span>YOUR BASKETS</span><h2>Saved baskets</h2></div><p>{portfolios.length} available</p></div><div className="portfolio-grid">{portfolios.map((portfolio) => <article className="portfolio-tile" key={portfolio.id}><button className="portfolio-open" onClick={() => router.push(`/etf/${portfolio.id}`)}><BarChart3 size={22} /><h3>{portfolio.name}</h3><p>{portfolio.description || "Custom basket allocation"}</p><footer>{portfolio.holdings.length} holdings <ArrowRight size={15} /></footer></button><button className="tile-delete" aria-label={`Delete ${portfolio.name}`} onClick={() => removePortfolio(portfolio)} disabled={!!busy}><Trash2 size={15} /></button></article>)}<button className="portfolio-tile add-tile" onClick={() => router.push("/etf/new")}><CirclePlus size={24} /><h3>Create a basket</h3><p>Start with stocks or listed ETFs.</p></button></div></Shell>;
  return <Shell {...shellProps}>
    {error && <div className="message error"><span>{error}</span><button onClick={() => setError("")}><X size={15} /></button></div>}{notice && <div className="message success"><span><Check size={15} />{notice}</span><button onClick={() => setNotice("")}><X size={15} /></button></div>}
    <header className="portfolio-header"><div><span>CONTAINER BUILDER</span><input className="title-input" aria-label="Portfolio name" value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /><input className="description-input" aria-label="Portfolio description" placeholder="Describe this portfolio" value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></div><div className="container-actions">{selected && <button className="delete-container" onClick={() => removePortfolio(selected)} disabled={!!busy}><Trash2 size={15} /> Delete</button>}<button onClick={async () => { try { setBusy("save"); await save(); setNotice("Container saved."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save."); } finally { setBusy(""); } }} disabled={!valid || !!busy}>{busy === "save" ? <Loader2 className="spin" size={15} /> : <Check size={15} />} Save container</button></div></header>
    <div className="builder-layout"><section className="card holdings-card"><div className="card-title"><div><span>01 · ALLOCATION</span><h2>Holdings & weights</h2></div><strong className={valid ? "weight-ok" : ""}>{allocationMode === "percent" ? `${total * 100}%` : money(total * config.initial_capital)}</strong></div><ThesisChat onCreate={createFromThesis} /><div className="ticker-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search stock or ETF ticker (e.g. DRAM, MAGS, VTI)" aria-label="Search stock or ETF ticker" /></div>{matches.length > 0 && <div className="search-results">{matches.map((item) => <button key={item.ticker} onClick={() => addHolding(item)}><strong>{item.ticker}</strong><span>{item.company_name}</span><Plus size={15} /></button>)}</div>}<div className="weight-tools"><span>{draft.holdings.length} holdings</span><div><button className="optimize-weights" onClick={optimizeWeights} disabled={!valid || !!busy} title="Searches whole-percent allocations over the selected backtest period"><SlidersHorizontal size={13} /> {busy === "optimize" ? "Optimizing" : "Optimize weights"}</button><button className={allocationMode === "percent" ? "active-range" : ""} onClick={() => { setAllocationMode("percent"); setAllocationInputs({}); }}>Percentage</button><button className={allocationMode === "dollars" ? "active-range" : ""} onClick={() => { setAllocationMode("dollars"); setAllocationInputs({}); }}>Dollar amount</button></div></div><div className="holding-list">{draft.holdings.map((holding, index) => <div className="holding-row" key={holding.ticker}><div><strong>{holding.ticker}</strong><span>{holding.company_name}</span></div><label><input aria-label={`${holding.ticker} allocation`} type="text" inputMode="decimal" placeholder={allocationMode === "percent" ? "0" : "$0"} value={allocationValue(holding)} onChange={(event) => changeAllocation(index, event.target.value)} /><small>{allocationMode === "percent" ? "%" : "$"}</small></label><button aria-label={`Remove ${holding.ticker}`} className="remove-holding" onClick={() => setDraft({ ...draft, holdings: draft.holdings.filter((_, itemIndex) => itemIndex !== index) })}><Trash2 size={15} /></button></div>)}{draft.holdings.length === 0 && <div className="empty-state">Describe a thesis above, or search stocks and listed ETFs to begin building this basket.</div>}</div></section>
      <aside className="card config-card"><div className="card-title"><div><span>02 · BACKTEST</span><h2>Simulation setup</h2></div></div><label>Benchmark<select value={config.benchmark} onChange={(event) => setConfig({ ...config, benchmark: event.target.value as Config["benchmark"] })}><option value="SPY">SPY · S&P 500</option><option value="QQQ">QQQ · Nasdaq 100</option></select></label><div className="entry-periods" role="tablist" aria-label="Backtest entry period">{ENTRY_PERIODS.map(([label, adjust]) => <button key={label} role="tab" aria-selected={false} onClick={() => setEntryPeriod(adjust)}>{label}</button>)}</div><div className="two-col"><label>Start date<input type="date" value={config.start_date} onChange={(event) => setConfig({ ...config, start_date: event.target.value })} /></label><label>End date<input type="date" value={config.end_date} onChange={(event) => setConfig({ ...config, end_date: event.target.value })} /></label></div><label>Rebalance<select value={config.rebalance_frequency} onChange={(event) => setConfig({ ...config, rebalance_frequency: event.target.value as Config["rebalance_frequency"] })}><option value="none">Buy and hold</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option></select></label><label>Starting capital<input type="number" min="1" value={config.initial_capital} onChange={(event) => setConfig({ ...config, initial_capital: Number(event.target.value) })} /></label><label>Transaction cost (bps)<input type="number" min="0" value={config.commission_bps} onChange={(event) => setConfig({ ...config, commission_bps: Number(event.target.value) })} /></label><label>Slippage (bps)<input type="number" min="0" value={config.slippage_bps} onChange={(event) => setConfig({ ...config, slippage_bps: Number(event.target.value) })} /></label><button className="primary run-button" onClick={() => runBacktest()} disabled={!valid || !!busy || activeJob}>{activeJob || busy === "backtest" ? <Loader2 className="spin" size={16} /> : <BarChart3 size={16} />}{activeJob ? "Running backtest" : "Run backtest"}</button></aside></div>
    {selected && <section className="paper-section"><div className="section-heading"><div><span>03 · PAPER TRADING</span><h2>Deploy this bucket</h2></div><p>Alpaca Paper · virtual funds only</p></div><div className="card paper-card"><div className="paper-deploy"><div><h3>Buy this target allocation</h3><p>Orders are attached to this bucket, use market buys, and do not rebalance existing positions.</p></div><label>Investment<input aria-label="Paper investment" type="number" min="1" step="1" value={paperInvestment} onChange={(event) => setPaperInvestment(event.target.value)} /></label><button className="primary" onClick={previewPaperDeployment} disabled={!valid || !!busy}>{busy === "paper-preview" ? <Loader2 className="spin" size={16} /> : "Preview paper order"}</button></div>{paperPreview && <div className="paper-preview"><div><strong>Review before paper submission</strong><small>{paperPreview.warning}</small></div><ul>{paperPreview.orders.map((order) => <li key={order.client_order_id}><b>{order.symbol}</b><span>{money(Number(order.notional))} market buy</span></li>)}</ul><button className="primary" onClick={submitPaperDeployment} disabled={!!busy}>{busy === "paper-submit" ? <Loader2 className="spin" size={16} /> : "Submit to paper trading"}</button></div>}<div className="paper-history"><div><h3>Bucket paper activity</h3><button onClick={refreshPaperActivity} disabled={!!busy}>{busy === "paper-refresh" ? "Refreshing…" : "Refresh status"}</button></div>{paperActivity.length ? <div className="paper-list">{paperActivity.map((preview) => <article key={preview.id}><header><span>{money(preview.investment)} deployment</span><small>{new Date(preview.created_at).toLocaleString()}</small></header>{preview.orders.length ? preview.orders.map((order, index) => <p key={`${preview.id}-${index}`}><b>{order.intent?.symbol ?? "Order"}</b><span>{order.status}{order.filled_qty ? ` · ${order.filled_qty} filled` : ""}</span></p>) : <p><span>Preview not submitted</span></p>}</article>)}</div> : <div className="paper-empty">No paper orders for this bucket yet.</div>}</div></div></section>}
    <section className="results-section"><div className="section-heading"><div><span>{selected ? "04" : "03"} · RESULTS</span><h2>Portfolio performance</h2></div>{result?.status === "completed" && <p>{result.config.start_date} - {result.config.end_date}</p>}</div><div className="entry-scenarios"><span>Assume entry:</span>{ENTRY_PERIODS.map(([label, adjust]) => <button key={label} onClick={() => runEntryPeriod(adjust)} disabled={!valid || !!busy || activeJob}>{label}</button>)}</div><div className="metrics-row">{[["Ending value", money(metrics.ending_value)], ["CAGR", pct(metrics.cagr)], ["Sharpe ratio", metrics.sharpe_ratio?.toFixed(2) ?? "-"], ["Maximum drawdown", pct(metrics.max_drawdown)]].map(([label, value]) => <div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="card chart-card">{series ? <><div className="chart-head"><div><h3>Equity curve</h3><p>Portfolio vs. {result?.config.benchmark}</p></div><div>{["1Y", "5Y", "MAX"].map((item) => <button className={range === item ? "active-range" : ""} key={item} onClick={() => setRange(item)}>{item}</button>)}</div></div><PerformanceChart data={series} /></> : <div className="empty-results">{activeJob ? <Loader2 className="spin" size={28} /> : <BarChart3 size={28} />}<h3>{activeJob ? "Calculating your backtest" : "No backtest yet"}</h3><p>{activeJob ? "Loading price history and simulating your target allocation." : "Set the allocation and simulation assumptions, then run a backtest."}</p></div>}</div><div className="walk-forward"><div><span>OUT-OF-SAMPLE CHECK</span><h3>Walk-forward validation</h3><p>Optimizes each training period, then scores the next 63 sessions it has not seen.</p></div><button onClick={runWalkForward} disabled={!valid || !!busy}>{busy === "walk-forward" ? <Loader2 className="spin" size={15} /> : <SlidersHorizontal size={15} />} Validate on unseen periods</button></div>{walkForward && <div className="card walk-forward-results"><div className="metrics-row">{[["Mean unseen return", pct(walkForward.summary.mean_unseen_return)], ["Benchmark mean", pct(walkForward.summary.mean_unseen_benchmark_return)], ["Win rate vs benchmark", pct(walkForward.summary.win_rate_vs_benchmark)], ["Median unseen return", pct(walkForward.summary.median_unseen_return)]].map(([label, value]) => <div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="walk-folds">{walkForward.folds.map((fold) => <p key={fold.test_start}><span>{fold.test_start} → {fold.test_end}</span><b>{pct(fold.unseen_total_return)} basket</b><small>{pct(fold.unseen_benchmark_return)} benchmark</small></p>)}</div><small className="walk-warning">{walkForward.warning}</small></div>}</section>
  </Shell>;
}

function Shell({ children, portfolios, onNew, userEmail, profileOpen, setProfileOpen, onSignOut }: { children: React.ReactNode; portfolios: ETF[]; onNew: () => void; userEmail: string; profileOpen: boolean; setProfileOpen: (open: boolean) => void; onSignOut: () => Promise<void> }) { const router = useRouter(); const initials = userEmail ? userEmail.slice(0, 1).toUpperCase() : "U"; return <div className="bare-app"><aside><button className="wordmark" onClick={() => router.push("/dashboard")}>aquarius<span>BASKETS</span></button><button className="new-container" onClick={onNew}><Plus size={16} /> New basket</button><nav><span>BASKETS</span>{portfolios.map((portfolio) => <button key={portfolio.id} onClick={() => router.push(`/etf/${portfolio.id}`)}>{portfolio.name}<ChevronRight size={14} /></button>)}</nav></aside><main><div className="profile-area"><button className="profile-trigger" aria-label="Open profile menu" onClick={() => setProfileOpen(!profileOpen)}>{userEmail ? initials : <UserRound size={17} />}</button>{profileOpen && <div className="profile-menu"><div><strong>{userEmail || "Not signed in"}</strong><span>{userEmail ? "Google account" : "Guest session"}</span></div><button onClick={onSignOut}><LogOut size={14} /> Sign out</button></div>}</div>{children}</main></div>; }
